const countries = {
    // AF: {code: "AF", flag: "🇦🇫", name: "Afghanistan"},
    // AX: {code: "AX", flag: "🇦🇽", name: "Åland Islands"},
    // AL: {code: "AL", flag: "🇦🇱", name: "Albania"},
    DZ: {code: "DZ", flag: "🇩🇿", name: "Algeria"},
    // AS: {code: "AS", flag: "🇦🇸", name: "American Samoa"},
    // AD: {code: "AD", flag: "🇦🇩", name: "Andorra"},
    // AO: {code: "AO", flag: "🇦🇴", name: "Angola"},
    // AI: {code: "AI", flag: "🇦🇮", name: "Anguilla"},
    // AQ: {code: "AQ", flag: "🇦🇶", name: "Antarctica"},
    // AG: {code: "AG", flag: "🇦🇬", name: "Antigua and Barbuda"},
    AR: {code: "AR", flag: "🇦🇷", name: "Argentina"},
    // AM: {code: "AM", flag: "🇦🇲", name: "Armenia"},
    // AW: {code: "AW", flag: "🇦🇼", name: "Aruba"},
    AU: {code: "AU", flag: "🇦🇺", name: "Australia"},
    AT: {code: "AT", flag: "🇦🇹", name: "Austria"},
    // AZ: {code: "AZ", flag: "🇦🇿", name: "Azerbaijan"},
    // BS: {code: "BS", flag: "🇧🇸", name: "Bahamas"},
    // BH: {code: "BH", flag: "🇧🇭", name: "Bahrain"},
    // BD: {code: "BD", flag: "🇧🇩", name: "Bangladesh"},
    // BB: {code: "BB", flag: "🇧🇧", name: "Barbados"},
    // BY: {code: "BY", flag: "🇧🇾", name: "Belarus"},
    BE: {code: "BE", flag: "🇧🇪", name: "Belgium"},
    // BZ: {code: "BZ", flag: "🇧🇿", name: "Belize"},
    // BJ: {code: "BJ", flag: "🇧🇯", name: "Benin"},
    // BM: {code: "BM", flag: "🇧🇲", name: "Bermuda"},
    // BT: {code: "BT", flag: "🇧🇹", name: "Bhutan"},
    // BO: {code: "BO", flag: "🇧🇴", name: "Bolivia"},
    // BQ: {code: "BQ", flag: "🇧🇶", name: "Bonaire, Sint Eustatius and Saba"},
    // BA: {code: "BA", flag: "🇧🇦", name: "Bosnia and Herzegovina"},
    // BW: {code: "BW", flag: "🇧🇼", name: "Botswana"},
    // BV: {code: "BV", flag: "🇧🇻", name: "Bouvet Island"},
    BR: {code: "BR", flag: "🇧🇷", name: "Brazil"},
    // IO: {code: "IO", flag: "🇮🇴", name: "British Indian Ocean Territory"},
    // BN: {code: "BN", flag: "🇧🇳", name: "Brunei Darussalam"},
    BG: {code: "BG", flag: "🇧🇬", name: "Bulgaria"},
    // BF: {code: "BF", flag: "🇧🇫", name: "Burkina Faso"},
    // BI: {code: "BI", flag: "🇧🇮", name: "Burundi"},
    // KH: {code: "KH", flag: "🇰🇭", name: "Cambodia"},
    // CM: {code: "CM", flag: "🇨🇲", name: "Cameroon"},
    CA: {code: "CA", flag: "🇨🇦", name: "Canada"},
    // CV: {code: "CV", flag: "🇨🇻", name: "Cape Verde"},
    // KY: {code: "KY", flag: "🇰🇾", name: "Cayman Islands"},
    // CF: {code: "CF", flag: "🇨🇫", name: "Central African Republic"},
    // TD: {code: "TD", flag: "🇹🇩", name: "Chad"},
    CL: {code: "CL", flag: "🇨🇱", name: "Chile"},
    CN: {code: "CN", flag: "🇨🇳", name: "China"},
    // CX: {code: "CX", flag: "🇨🇽", name: "Christmas Island"},
    // CC: {code: "CC", flag: "🇨🇨", name: "Cocos (Keeling) Islands"},
    // CO: {code: "CO", flag: "🇨🇴", name: "Colombia"},
    // KM: {code: "KM", flag: "🇰🇲", name: "Comoros"},
    // CK: {code: "CK", flag: "🇨🇰", name: "Cook Islands"},
    // CR: {code: "CR", flag: "🇨🇷", name: "Costa Rica"},
    HR: {code: "HR", flag: "🇭🇷", name: "Croatia"},
    CU: {code: "CU", flag: "🇨🇺", name: "Cuba"},
    // CW: {code: "CW", flag: "🇨🇼", name: "Curaçao"},
    CY: {code: "CY", flag: "🇨🇾", name: "Cyprus"},
    CZ: {code: "CZ", flag: "🇨🇿", name: "Czech Republic"},
    // CI: {code: "CI", flag: "🇨🇮", name: "Côte D'Ivoire"},
    DK: {code: "DK", flag: "🇩🇰", name: "Denmark"},
    // DJ: {code: "DJ", flag: "🇩🇯", name: "Djibouti"},
    // DM: {code: "DM", flag: "🇩🇲", name: "Dominica"},
    // DO: {code: "DO", flag: "🇩🇴", name: "Dominican Republic"},
    EC: {code: "EC", flag: "🇪🇨", name: "Ecuador"},
    EG: {code: "EG", flag: "🇪🇬", name: "Egypt"},
    SV: {code: "SV", flag: "🇸🇻", name: "El Salvador"},
    // GQ: {code: "GQ", flag: "🇬🇶", name: "Equatorial Guinea"},
    // ER: {code: "ER", flag: "🇪🇷", name: "Eritrea"},
    EE: {code: "EE", flag: "🇪🇪", name: "Estonia"},
    // ET: {code: "ET", flag: "🇪🇹", name: "Ethiopia"},
    // FK: {code: "FK", flag: "🇫🇰", name: "Falkland Islands (Malvinas)"},
    // FO: {code: "FO", flag: "🇫🇴", name: "Faroe Islands"},
    // FJ: {code: "FJ", flag: "🇫🇯", name: "Fiji"},
    FI: {code: "FI", flag: "🇫🇮", name: "Finland"},
    FR: {code: "FR", flag: "🇫🇷", name: "France"},
    // GF: {code: "GF", flag: "🇬🇫", name: "French Guiana"},
    // PF: {code: "PF", flag: "🇵🇫", name: "French Polynesia"},
    // TF: {code: "TF", flag: "🇹🇫", name: "French Southern Territories"},
    // GA: {code: "GA", flag: "🇬🇦", name: "Gabon"},
    // GM: {code: "GM", flag: "🇬🇲", name: "Gambia"},
    GE: {code: "GE", flag: "🇬🇪", name: "Georgia"},
    DE: {code: "DE", flag: "🇩🇪", name: "Germany"},
    GH: {code: "GH", flag: "🇬🇭", name: "Ghana"},
    // GI: {code: "GI", flag: "🇬🇮", name: "Gibraltar"},
    GR: {code: "GR", flag: "🇬🇷", name: "Greece"},
    GL: {code: "GL", flag: "🇬🇱", name: "Greenland"},
    // GD: {code: "GD", flag: "🇬🇩", name: "Grenada"},
    // GP: {code: "GP", flag: "🇬🇵", name: "Guadeloupe"},
    // GU: {code: "GU", flag: "🇬🇺", name: "Guam"},
    // GT: {code: "GT", flag: "🇬🇹", name: "Guatemala"},
    // GG: {code: "GG", flag: "🇬🇬", name: "Guernsey"},
    GN: {code: "GN", flag: "🇬🇳", name: "Guinea"},
    // GW: {code: "GW", flag: "🇬🇼", name: "Guinea-Bissau"},
    // GY: {code: "GY", flag: "🇬🇾", name: "Guyana"},
    // HT: {code: "HT", flag: "🇭🇹", name: "Haiti"},
    // HM: {code: "HM", flag: "🇭🇲", name: "Heard Island and Mcdonald Islands"},
    // HN: {code: "HN", flag: "🇭🇳", name: "Honduras"},
    HK: {code: "HK", flag: "🇭🇰", name: "Hong Kong"},
    HU: {code: "HU", flag: "🇭🇺", name: "Hungary"},
    IS: {code: "IS", flag: "🇮🇸", name: "Iceland"},
    IN: {code: "IN", flag: "🇮🇳", name: "India"},
    ID: {code: "ID", flag: "🇮🇩", name: "Indonesia"},
    IR: {code: "IR", flag: "🇮🇷", name: "Iran"},
    IQ: {code: "IQ", flag: "🇮🇶", name: "Iraq"},
    IE: {code: "IE", flag: "🇮🇪", name: "Ireland"},
    // IM: {code: "IM", flag: "🇮🇲", name: "Isle of Man"},
    // IL: {code: "IL", flag: "🇮🇱", name: "Israel"},
    IT: {code: "IT", flag: "🇮🇹", name: "Italy"},
    // JM: {code: "JM", flag: "🇯🇲", name: "Jamaica"},
    // JP: {code: "JP", flag: "🇯🇵", name: "Japan"},
    // JE: {code: "JE", flag: "🇯🇪", name: "Jersey"},
    JO: {code: "JO", flag: "🇯🇴", name: "Jordan"},
    // KZ: {code: "KZ", flag: "🇰🇿", name: "Kazakhstan"},
    KE: {code: "KE", flag: "🇰🇪", name: "Kenya"},
    // KI: {code: "KI", flag: "🇰🇮", name: "Kiribati"},
    // XK: {code: "XK", flag: "🇽🇰", name: "Kosovo"},
    KW: {code: "KW", flag: "🇰🇼", name: "Kuwait"},
    // KG: {code: "KG", flag: "🇰🇬", name: "Kyrgyzstan"},
    // LA: {code: "LA", flag: "🇱🇦", name: "Lao People's Democratic Republic"},
    // LV: {code: "LV", flag: "🇱🇻", name: "Latvia"},
    // LB: {code: "LB", flag: "🇱🇧", name: "Lebanon"},
    // LS: {code: "LS", flag: "🇱🇸", name: "Lesotho"},
    // LR: {code: "LR", flag: "🇱🇷", name: "Liberia"},
    // LY: {code: "LY", flag: "🇱🇾", name: "Libya"},
    LI: {code: "LI", flag: "🇱🇮", name: "Liechtenstein"},
    LT: {code: "LT", flag: "🇱🇹", name: "Lithuania"},
    LU: {code: "LU", flag: "🇱🇺", name: "Luxembourg"},
    // MO: {code: "MO", flag: "🇲🇴", name: "Macao"},
    MK: {code: "MK", flag: "🇲🇰", name: "Macedonia"},
    // MG: {code: "MG", flag: "🇲🇬", name: "Madagascar"},
    // MW: {code: "MW", flag: "🇲🇼", name: "Malawi"},
    MY: {code: "MY", flag: "🇲🇾", name: "Malaysia"},
    // MV: {code: "MV", flag: "🇲🇻", name: "Maldives"},
    // ML: {code: "ML", flag: "🇲🇱", name: "Mali"},
    // MT: {code: "MT", flag: "🇲🇹", name: "Malta"},
    // MH: {code: "MH", flag: "🇲🇭", name: "Marshall Islands"},
    // MQ: {code: "MQ", flag: "🇲🇶", name: "Martinique"},
    // MR: {code: "MR", flag: "🇲🇷", name: "Mauritania"},
    // MU: {code: "MU", flag: "🇲🇺", name: "Mauritius"},
    // YT: {code: "YT", flag: "🇾🇹", name: "Mayotte"},
    MX: {code: "MX", flag: "🇲🇽", name: "Mexico"},
    // FM: {code: "FM", flag: "🇫🇲", name: "Micronesia"},
    // MD: {code: "MD", flag: "🇲🇩", name: "Moldova"},
    // MC: {code: "MC", flag: "🇲🇨", name: "Monaco"},
    // MN: {code: "MN", flag: "🇲🇳", name: "Mongolia"},
    // ME: {code: "ME", flag: "🇲🇪", name: "Montenegro"},
    // MS: {code: "MS", flag: "🇲🇸", name: "Montserrat"},
    MA: {code: "MA", flag: "🇲🇦", name: "Morocco"},
    // MZ: {code: "MZ", flag: "🇲🇿", name: "Mozambique"},
    // MM: {code: "MM", flag: "🇲🇲", name: "Myanmar"},
    // NA: {code: "NA", flag: "🇳🇦", name: "Namibia"},
    // NR: {code: "NR", flag: "🇳🇷", name: "Nauru"},
    // NP: {code: "NP", flag: "🇳🇵", name: "Nepal"},
    NL: {code: "NL", flag: "🇳🇱", name: "Netherlands"},
    // NC: {code: "NC", flag: "🇳🇨", name: "New Caledonia"},
    NZ: {code: "NZ", flag: "🇳🇿", name: "New Zealand"},
    // NI: {code: "NI", flag: "🇳🇮", name: "Nicaragua"},
    // NE: {code: "NE", flag: "🇳🇪", name: "Niger"},
    NG: {code: "NG", flag: "🇳🇬", name: "Nigeria"},
    // NU: {code: "NU", flag: "🇳🇺", name: "Niue"},
    // NF: {code: "NF", flag: "🇳🇫", name: "Norfolk Island"},
    // KP: {code: "KP", flag: "🇰🇵", name: "North Korea"},
    // MP: {code: "MP", flag: "🇲🇵", name: "Northern Mariana Islands"},
    // NO: {code: "NO", flag: "🇳🇴", name: "Norway"},
    // OM: {code: "OM", flag: "🇴🇲", name: "Oman"},
    PK: {code: "PK", flag: "🇵🇰", name: "Pakistan"},
    // PW: {code: "PW", flag: "🇵🇼", name: "Palau"},
    PS: {code: "PS", flag: "🇵🇸", name: "Palestinian Territory"},
    PA: {code: "PA", flag: "🇵🇦", name: "Panama"},
    // PG: {code: "PG", flag: "🇵🇬", name: "Papua New Guinea"},
    // PY: {code: "PY", flag: "🇵🇾", name: "Paraguay"},
    // PE: {code: "PE", flag: "🇵🇪", name: "Peru"},
    PH: {code: "PH", flag: "🇵🇭", name: "Philippines"},
    // PN: {code: "PN", flag: "🇵🇳", name: "Pitcairn"},
    PL: {code: "PL", flag: "🇵🇱", name: "Poland"},
    PT: {code: "PT", flag: "🇵🇹", name: "Portugal"},
    PR: {code: "PR", flag: "🇵🇷", name: "Puerto Rico"},
    QA: {code: "QA", flag: "🇶🇦", name: "Qatar"},
    RO: {code: "RO", flag: "🇷🇴", name: "Romania"},
    RU: {code: "RU", flag: "🇷🇺", name: "Russia"},
    // RW: {code: "RW", flag: "🇷🇼", name: "Rwanda"},
    // RE: {code: "RE", flag: "🇷🇪", name: "Réunion"},
    // BL: {code: "BL", flag: "🇧🇱", name: "Saint Barthélemy"},
    // SH: {code: "SH", flag: "🇸🇭", name: "Saint Helena, Ascension and Tristan Da Cunha"},
    // KN: {code: "KN", flag: "🇰🇳", name: "Saint Kitts and Nevis"},
    // LC: {code: "LC", flag: "🇱🇨", name: "Saint Lucia"},
    // MF: {code: "MF", flag: "🇲🇫", name: "Saint Martin (French Part)"},
    // PM: {code: "PM", flag: "🇵🇲", name: "Saint Pierre and Miquelon"},
    // VC: {code: "VC", flag: "🇻🇨", name: "Saint Vincent and The Grenadines"},
    // WS: {code: "WS", flag: "🇼🇸", name: "Samoa"},
    // SM: {code: "SM", flag: "🇸🇲", name: "San Marino"},
    // ST: {code: "ST", flag: "🇸🇹", name: "Sao Tome and Principe"},
    SA: {code: "SA", flag: "🇸🇦", name: "Saudi Arabia"},
    SN: {code: "SN", flag: "🇸🇳", name: "Senegal"},
    RS: {code: "RS", flag: "🇷🇸", name: "Serbia"},
    // SC: {code: "SC", flag: "🇸🇨", name: "Seychelles"},
    // SL: {code: "SL", flag: "🇸🇱", name: "Sierra Leone"},
    SG: {code: "SG", flag: "🇸🇬", name: "Singapore"},
    // SX: {code: "SX", flag: "🇸🇽", name: "Sint Maarten (Dutch Part)"},
    SK: {code: "SK", flag: "🇸🇰", name: "Slovakia"},
    SI: {code: "SI", flag: "🇸🇮", name: "Slovenia"},
    // SB: {code: "SB", flag: "🇸🇧", name: "Solomon Islands"},
    // SO: {code: "SO", flag: "🇸🇴", name: "Somalia"},
    ZA: {code: "ZA", flag: "🇿🇦", name: "South Africa"},
    // GS: {code: "GS", flag: "🇬🇸", name: "South Georgia"},
    KR: {code: "KR", flag: "🇰🇷", name: "South Korea"},
    // SS: {code: "SS", flag: "🇸🇸", name: "South Sudan"},
    ES: {code: "ES", flag: "🇪🇸", name: "Spain"},
    // LK: {code: "LK", flag: "🇱🇰", name: "Sri Lanka"},
    // SD: {code: "SD", flag: "🇸🇩", name: "Sudan"},
    // SR: {code: "SR", flag: "🇸🇷", name: "Suriname"},
    // SJ: {code: "SJ", flag: "🇸🇯", name: "Svalbard and Jan Mayen"},
    // SZ: {code: "SZ", flag: "🇸🇿", name: "Swaziland"},
    SE: {code: "SE", flag: "🇸🇪", name: "Sweden"},
    CH: {code: "CH", flag: "🇨🇭", name: "Switzerland"},
    // SY: {code: "SY", flag: "🇸🇾", name: "Syrian Arab Republic"},
    TW: {code: "TW", flag: "🇹🇼", name: "Taiwan"},
    // TJ: {code: "TJ", flag: "🇹🇯", name: "Tajikistan"},
    // TZ: {code: "TZ", flag: "🇹🇿", name: "Tanzania"},
    // TH: {code: "TH", flag: "🇹🇭", name: "Thailand"},
    // TL: {code: "TL", flag: "🇹🇱", name: "Timor-Leste"},
    // TG: {code: "TG", flag: "🇹🇬", name: "Togo"},
    // TK: {code: "TK", flag: "🇹🇰", name: "Tokelau"},
    // TO: {code: "TO", flag: "🇹🇴", name: "Tonga"},
    // TT: {code: "TT", flag: "🇹🇹", name: "Trinidad and Tobago"},
    TN: {code: "TN", flag: "🇹🇳", name: "Tunisia"},
    TR: {code: "TR", flag: "🇹🇷", name: "Turkey"},
    // TM: {code: "TM", flag: "🇹🇲", name: "Turkmenistan"},
    // TC: {code: "TC", flag: "🇹🇨", name: "Turks and Caicos Islands"},
    // TV: {code: "TV", flag: "🇹🇻", name: "Tuvalu"},
    UG: {code: "UG", flag: "🇺🇬", name: "Uganda"},
    UA: {code: "UA", flag: "🇺🇦", name: "Ukraine"},
    AE: {code: "AE", flag: "🇦🇪", name: "United Arab Emirates"},
    GB: {code: "GB", flag: "🇬🇧", name: "United Kingdom"},
    US: {code: "US", flag: "🇺🇸", name: "United States"},
    // UM: {code: "UM", flag: "🇺🇲", name: "United States Minor Outlying Islands"},
    // UY: {code: "UY", flag: "🇺🇾", name: "Uruguay"},
    // UZ: {code: "UZ", flag: "🇺🇿", name: "Uzbekistan"},
    // VU: {code: "VU", flag: "🇻🇺", name: "Vanuatu"},
    // VA: {code: "VA", flag: "🇻🇦", name: "Vatican City"},
    // VE: {code: "VE", flag: "🇻🇪", name: "Venezuela"},
    VN: {code: "VN", flag: "🇻🇳", name: "Viet Nam"},
    // VG: {code: "VG", flag: "🇻🇬", name: "Virgin Islands, British"},
    // VI: {code: "VI", flag: "🇻🇮", name: "Virgin Islands, U.S."},
    // WF: {code: "WF", flag: "🇼🇫", name: "Wallis and Futuna"},
    // EH: {code: "EH", flag: "🇪🇭", name: "Western Sahara"},
    // YE: {code: "YE", flag: "🇾🇪", name: "Yemen"},
    // ZM: {code: "ZM", flag: "🇿🇲", name: "Zambia"},
    // ZW: {code: "ZW", flag: "🇿🇼", name: "Zimbabwe"}
};
